// Alert Types
export const SET_ALERT = 'ALERT:SET';
export const REMOVE_ALERT = 'ALERT:REMOVE';

// Authentication Types
export const USER_LOADED = 'USER:LOADED';
export const AUTH_ERROR = 'AUTH:ERROR';
export const LOGIN_SUCCESS = 'USER:LOGIN_SUCCESS';
export const LOGIN_ERROR = 'USER:LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'USER:SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'USER:SIGNOUT_ERROR';

// Service Types
export const CREATE_SERVICE_SUCCESS = 'SERVICE:CREATE_SUCCESS';
export const CREATE_SERVICE_ERROR = 'SERVICE:CREATE_ERROR';
export const GET_SERVICE_SUCCESS = 'SERVICE:GET_SUCCESS';
export const GET_SERVICE_ERROR = 'SERVICE:GET_ERROR';
export const UPDATE_SERVICE_SUCCESS = 'SERVICE:UPDATE_SUCCESS';
export const UPDATE_SERVICE_ERROR = 'SERVICE:UPDATE_ERROR';
export const DELETE_SERVICE_SUCCESS = 'SERVICE:DELETE_SUCCESS';
export const DELETE_SERVICE_ERROR = 'SERVICE:DELETE_ERROR';
