export const SET_ALERT = 'ALERT:SET';
export const REMOVE_ALERT = 'ALERT:REMOVE';
export const USER_LOADED = 'USER:LOADED';
export const AUTH_ERROR = 'AUTH:ERROR';
export const LOGIN_SUCCESS = 'USER:LOGIN_SUCCESS';
export const LOGIN_ERROR = 'USER:LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'USER:SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'USER:SIGNOUT_ERROR';
